### ISSUE TITLE
Persistent notebooks

### ISSUE THREAD

**Issue by asophila** [xtreamsrl/polynote-docker#4]
The data volume works flawlessly, but there's no option to have a persistent volumen with notebooks.

Is that possible?

Thanks

**Comment by rmaganza** [comment]
Thank you for the feedback! 
Sure thing, I will look into it soon.

We created this mainly to experiment with the platform and we did not feel the need for persistence back then but it's surely an important feature!

**Comment by rmaganza** [comment]
Hey, you can find this implemented in [this branch](/xtreamsrl/polynote-docker/tree/feat/notebook-persistence).

You can try it out from there. We will merge soon if everything is ok. :)

**Comment by asophila** [comment]
Cool!.  
I'll test it ASAP.

Thanks!!

**Comment by asophila** [comment]
Works like a charm!

Many thanks!!
